title: Kamalnath Sathyamurthy # your name (or website title) here
logo: "" # your photo (or logo) here
description: > 
  Data Scientist with over 6 years of broad-based experience in ETL (Extract, Transform and Load) testing of data intensive applications, creating and deploying complex user stories to build substantial deliverables as per business requirements | Proficient in creating effective visualizations and developing complex forecast and regression models | Thriving to improve myself by engaging in challenging research areas and business needs.
  <br></br>
  Master's in Data Science @ The State University of New York, Buffalo
  <br></br>
  
  <a href="https:www.linkedin.com/in/kamalnathsathya/">View My LinkedIn Profile</a> 
  <br></br>
  

